# Generated by Django 6.0 on 2025-12-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_officeip_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_date',
        ),
    ]
