# Generated by Django 6.0 on 2025-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_remove_leaverequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
