# Generated by Django 6.0 on 2025-12-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_adduser_role_alter_adduser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeIP',
        ),
    ]
