# Generated by Django 6.0 on 2025-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_delete_officeip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='role',
            field=models.CharField(choices=[('It', 'It'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designerr'), ('Digital Marketing', 'Digital Marketing')], default='Frontend', max_length=30),
        ),
    ]
