# Generated by Django 6.0 on 2025-12-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_alter_adduser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
    ]
