# Generated by Django 6.0 on 2025-12-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_officeip_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
    ]
