# Generated by Django 6.0 on 2025-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_attendance_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
