# Generated by Django 6.0 on 2025-12-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0010_adduser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
