# Generated by Django 6.0 on 2025-12-26 03:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_holiday_leaverequest_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
