# Generated by Django 6.0 on 2025-12-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0012_alter_adduser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
