# Generated by Django 6.0 on 2025-12-26 09:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_alter_leaverequest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
