# Generated by Django 6.0 on 2025-12-28 06:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_alter_leaverequest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
