# Generated by Django 6.0 on 2025-12-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0016_alter_adduser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adduser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='adduser',
            name='employee_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
