# Generated by Django 6.0 on 2025-12-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0017_adduser_address_adduser_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='alternate_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('paid', 'paid Leave'), ('unpaid', 'unpaid Leave')], max_length=20),
        ),
    ]
