# Generated by Django 6.0 on 2026-01-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0020_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.role'),
        ),
    ]
