# Generated by Django 6.0 on 2026-01-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0021_alter_adduser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
