# Generated by Django 6.0 on 2026-01-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0022_delete_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeIP',
        ),
    ]
